project:
  type: book

book:
  title: "AMSI-TUTORIALS"
  author: "Mikel Vandeloise"
  date: "8/13/2025"
  chapters:
    - index.qmd
    - 01-intro-modelling.qmd
    - 02-intro-uml.qmd
    - 03-class-diagrams.qmd
    - 04-practical-exercises-class-diagrams.qmd
    - 05-practical-exercises-object-diagrams.qmd
    - 06-ocl.qmd
    - 07-practical-exercises-ocl.qmd
    - 08-state-machine-diagrams.qmd
    - 09-practical-exercises-state-machine-diagrams.qmd


bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



